---
- name: gather operating system variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: sshd

- name: install openssh-server openssh-client
  package:
    name: "{{ ssh_packages }}"
    state: present
  environment: "{{ proxy_env }}"
  become: true
  tags: sshd

- name: configure /etc/ssh/ssh_config & /etc/sshd/sshd_config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - { src: ssh.config.j2, dest: /etc/ssh/ssh_config }
    - { src: sshd.config.j2, dest: /etc/ssh/sshd_config }
  notify: restart ssh
  become: true
  tags: sshd

- name: start and enable sshd service
  service:
    name: "{{ ssh_service }}"
    state: started
    enabled: true
  become: true
  tags: sshd
